name: Docker Build and Run

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build --progress=plain -t mydockerapp ./python-image

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 --name mydockerapp-container mydockerapp
          docker ps
          sleep 10  # Wait for 10 seconds to ensure Flask is fully up

      - name: Test Flask API with curl
        run: |
          curl --max-time 30 http://localhost:5000/
          curl --max-time 30 http://localhost:5000/time
          curl --max-time 30 http://localhost:5000/status
          curl --max-time 30 http://localhost:5000/quote
          curl --max-time 30 "http://localhost:5000/greet?name=John"

      - name: Check Docker container logs
        run: |
          docker logs mydockerapp-container
